### ISSUE TITLE
Add CI scripts

### ISSUE THREAD

**Issue by vania-pooh** [pychik/lightning_py#4]
Need to add scripts that do the following:
* [x] Run tests (`pytest` and static analyzer for pep8 rules) on pull requests
* [x] Run tests on merge changes to master branch
* [x] Run tests and publish to pypi repository on new tag (release)

**Comment by pychik** [comment]
still release on pypi not made. need asisst

**Comment by pychik** [comment]
TestsPypi release ready, rest to do is ci on release 

in 27b758efd5412adfe9cff4f1b854d5a436ec3cf4

**Comment by pychik** [comment]
all tasks  done in 627286714088c0293aa0072d8af3c38f02fdcdba

**Comment by vania-pooh** [comment]
Closing then.
