### ISSUE TITLE
Implement timeouts methods

### ISSUE THREAD

**Issue by vania-pooh** [pychik/lightning_py#5]
Implement methods from [timeouts](https://www.w3.org/TR/webdriver/#timeouts) section of Webdriver spec. Use https://stackoverflow.com/questions/2627002/whats-the-pythonic-way-to-use-getters-and-setters
* [x] `@property + @attribute.setter driver.timeouts().implicit_wait_timeout`
* [x] `@property + @attribute.setter driver.timeouts().page_load_timeout`
* [x] `@property + @attribute.setter driver.timeouts().script_timeout` using `Optional` for getter

**Comment by pychik** [comment]
Functionality ready and tested

**Comment by vania-pooh** [comment]
fixed in 7df92b0df035d52a49685d11fdb3f155203f7311

**Comment by vania-pooh** [comment]
Done.
